/** Signal Utility design reminder: trust content uses calm editorial pages and explicit claims. */
import { Link } from "wouter";
import { ArrowRight, CheckCircle2, LockKeyhole, ScanLine, ShieldCheck } from "lucide-react";
import SiteShell from "@/components/SiteShell";
import Seo from "@/components/Seo";
const privacyImage = "/manus-storage/convert-any-image-privacy_8d7e1e2b.jpg";

export function About() { return <SiteShell><Seo title="À propos" description="Découvrez l’approche locale de Convert Any Image : des conversions dans le navigateur et des fichiers qui restent sur l’appareil."/><main><section className="mx-auto grid max-w-[1440px] lg:grid-cols-2"><div className="relative px-5 py-16 lg:px-20 lg:py-28"><span className="absolute left-5 top-16 h-11 w-11 border-l border-t border-[#b7f840] lg:left-20 lg:top-20"/><p className="label">NOTRE PRINCIPE / 01</p><h1 className="font-display mt-5 text-5xl font-bold leading-[.93] tracking-[-.075em] lg:text-7xl">Votre image reste<br/><span>votre image.</span></h1><p className="mt-8 max-w-lg text-lg leading-7 text-[#41525d]">Convert Any Image a été conçu pour retirer une friction devenue habituelle : envoyer un fichier personnel vers un service distant simplement pour changer son format ou réduire son poids.</p><div className="mt-8 flex items-center gap-3 text-[.64rem] font-bold tracking-[.14em] text-[#5c7820]"><span className="grid h-6 w-6 place-items-center border border-[#5c7820]">✓</span> TRAITEMENT LOCAL VÉRIFIABLE</div></div><div className="relative min-h-[360px] bg-[#132432]"><img src={privacyImage} alt="Illustration d’un appareil dans un périmètre de traitement local" className="h-full w-full object-cover"/><span className="absolute bottom-5 left-5 border border-[#b7f840] bg-[#132432]/85 px-3 py-2 text-[.6rem] font-bold tracking-[.14em] text-[#b7f840]">DEVICE BOUND / 01</span></div></section><section className="border-y border-[#132432]/10 bg-[#e9e4da] px-5 py-14 lg:px-10"><div className="mx-auto grid max-w-[1220px] gap-10 md:grid-cols-3"><Info icon={LockKeyhole} title="Exécuté ici" text="Le traitement compatible s’exécute dans le navigateur, sur l’appareil qui a ouvert la page."/><Info icon={ScanLine} title="États visibles" text="Le décodage, la conversion et les exceptions sont signalés par fichier plutôt que dissimulés."/><Info icon={ShieldCheck} title="Promesse limitée" text="Lorsqu’un décodeur spécialisé n’est pas prêt, l’interface l’indique et ne prétend pas convertir."/></div></section><section className="mx-auto max-w-[1220px] px-5 py-16 lg:px-10"><h2 className="font-display max-w-3xl text-4xl font-bold leading-[.98] tracking-[-.07em]">Un outil de passage, pas une destination pour vos fichiers.</h2><Link href="/" className="action-primary mt-8">Ouvrir la table de conversion <ArrowRight className="h-4 w-4"/></Link></section></main></SiteShell>; }
function Info({ icon: Icon, title, text }: { icon: typeof LockKeyhole; title: string; text: string }) { return <div><Icon className="h-6 w-6 text-[#5c7820]"/><h2 className="font-display mt-5 text-xl font-bold tracking-[-.045em]">{title}</h2><p className="mt-3 text-sm leading-6 text-[#52616a]">{text}</p></div>; }

const legalContent: Record<string, { title: string; intro: string; sections: { heading: string; text: string }[] }> = {
  privacy: { title: "Confidentialité", intro: "Notre principe est simple : vos images sont traitées dans votre navigateur et ne sont pas téléversées vers nos serveurs par l’outil de conversion.", sections: [{ heading: "Traitement des images", text: "Les fichiers sélectionnés sont lus par votre navigateur afin d’effectuer les opérations compatibles localement. Ils restent dans la mémoire de votre session et ne sont pas transmis à Convert Any Image pour être convertis." }, { heading: "Données techniques", text: "Nous pouvons recueillir des données d’usage agrégées et non directement identifiantes afin de mesurer le fonctionnement du site. Elles ne contiennent pas le contenu de vos images." }, { heading: "Vos choix", text: "Vous pouvez supprimer les données de site dans votre navigateur à tout moment. Fermer l’onglet met fin à la session de traitement locale." }] },
  terms: { title: "Conditions d’utilisation", intro: "Convert Any Image fournit un outil de traitement d’images côté navigateur, dans les limites des fonctions et des formats réellement disponibles sur votre appareil.", sections: [{ heading: "Usage du service", text: "Vous êtes responsable des fichiers que vous choisissez de traiter et confirmez disposer des droits nécessaires pour les manipuler." }, { heading: "Disponibilité des formats", text: "Le support d’un format dépend de l’implémentation du navigateur et des décodeurs locaux disponibles. Les fonctions peuvent évoluer sans garantie de résultat pour un fichier particulier." }, { heading: "Limitation", text: "Vérifiez toujours le fichier téléchargé avant de remplacer un original important. Conservez une copie de vos fichiers source." }] },
  cookies: { title: "Politique de cookies", intro: "Le traitement d’images ne dépend pas de cookies publicitaires. Les cookies ou technologies similaires éventuellement employés servent à la sécurité, aux préférences et à une mesure agrégée du site.", sections: [{ heading: "Fonctionnement", text: "Les préférences d’interface peuvent être conservées dans votre navigateur afin de fluidifier votre prochaine visite." }, { heading: "Mesure agrégée", text: "Une mesure d’audience peut être utilisée pour comprendre l’usage global du site, sans analyser le contenu de vos fichiers locaux." }, { heading: "Gérer les cookies", text: "Vous pouvez supprimer ou bloquer les cookies dans les paramètres de votre navigateur. Certaines préférences peuvent alors devoir être redéfinies." }] },
};
export function Legal({ kind }: { kind: "privacy" | "terms" | "cookies" }) { const page = legalContent[kind]; return <SiteShell><Seo title={page.title} description={page.intro}/><main className="mx-auto max-w-[980px] px-5 py-16 lg:py-24"><p className="label">INFORMATIONS LÉGALES</p><h1 className="font-display mt-4 text-5xl font-bold tracking-[-.075em] lg:text-7xl">{page.title}</h1><p className="mt-8 max-w-2xl font-serif text-2xl leading-9 text-[#41525d]">{page.intro}</p><div className="mt-14 divide-y divide-[#132432]/12 border-y border-[#132432]/12">{page.sections.map((section, index) => <section key={section.heading} className="grid gap-4 py-8 md:grid-cols-[170px_minmax(0,1fr)]"><p className="label text-[#5c7820]">0{index + 1}</p><div><h2 className="font-display text-2xl font-bold tracking-[-.05em]">{section.heading}</h2><p className="mt-3 max-w-xl text-[1.02rem] leading-7 text-[#41525d]">{section.text}</p></div></section>)}</div><p className="mt-10 flex items-center gap-2 text-sm text-[#65727b]"><CheckCircle2 className="h-4 w-4 text-[#5c7820]"/>Dernière mise à jour : août 2026.</p></main></SiteShell>; }
