/** Signal Utility design reminder: article guidance must be practical, evidence-aware and explicit when browser support varies. */
export type ArticleSection = { heading: string; paragraphs: string[]; bullets?: string[] };
export type ArticleVisual = { src: string; alt: string; title: string };
export type BlogArticle = { slug: string; category: string; title: string; metaTitle: string; keyword: string; description: string; lead: string; reading: string; tool: "convert" | "compress"; sections: ArticleSection[]; related: string[]; visual?: ArticleVisual };

export const articles: BlogArticle[] = [
  {
    slug: "open-psd-without-photoshop", category: "FORMAT FIXERS", title: "How to Open PSD Files Without Photoshop", metaTitle: "Open PSD Files Without Photoshop (Free Guide)", keyword: "how to open psd file without photoshop free", description: "Learn practical ways to open PSD files without Photoshop, export a compatible copy and protect the original layered file.", lead: "A PSD file is useful because it preserves layers, but that also makes it awkward to preview when Photoshop is not available.", reading: "6 min", tool: "convert", related: ["heic-to-jpg-windows-android", "webp-to-jpg-any-device"], visual: { src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663909203131/NTJgmUwGtNPKHJOW.jpg", alt: "Layered visual sheets representing a Photoshop PSD preview workflow", title: "PSD Layer Preview Workflow" },
    sections: [
      { heading: "Start with a safe copy", paragraphs: ["We know how annoying it is to receive a PSD when you only need to inspect an image or share a quick preview. Keep the original PSD untouched and work from a duplicate whenever possible.", "A browser preview depends on the file and decoder available on that device. If a PSD cannot be opened in the browser, use a desktop graphics application that can read PSD files rather than renaming the file extension."], bullets: ["Keep the original layered PSD as the source of truth", "Export a JPG or PNG copy for review and sharing", "Check the exported copy visually before sending it"] },
      { heading: "Choose the right preview format", paragraphs: ["JPG is useful for photographs and simple review copies. PNG is better when the exported design needs crisp text, line art or transparent areas. Neither format retains editable PSD layers.", "For supported input files, the free online image converter can make a local preview copy without sending the file through an upload form."], bullets: ["Use JPG for compact photographic previews", "Use PNG for graphics and transparent elements", "Use PDF when a single shareable page is more helpful than an image"] },
      { heading: "Avoid damaging the working file", paragraphs: ["Do not overwrite the PSD with an exported image. The flattening process removes layers, adjustment settings and other editing information that may be needed later.", "If the goal is collaboration, label the export clearly, such as project-preview.jpg, and keep the PSD in the project folder." ] },
    ],
  },
  {
    slug: "heic-to-jpg-windows-android", category: "FORMAT FIXERS", title: "Convert HEIC to JPG on Windows and Android", metaTitle: "Convert HEIC to JPG on Windows & Android", keyword: "convert heic to jpg on windows 10 free", description: "Convert HEIC photos to JPG on Windows or Android with practical steps, privacy tips and compatibility checks.", lead: "HEIC keeps iPhone photos compact, but many Windows, Android and web workflows still ask for JPG.", reading: "6 min", tool: "convert", related: ["webp-to-jpg-any-device", "safe-free-image-converters"], visual: { src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663909203131/iwxRKIqypFyoEwsf.jpg", alt: "Phone photo card converting into a compatible JPG print", title: "HEIC-to-JPG Compatibility Workflow" },
    sections: [
      { heading: "Why HEIC can be difficult to share", paragraphs: ["A photo can look fine on an iPhone yet fail in an older form, messaging client or desktop app because the destination does not recognise HEIC. Converting a copy to JPG creates a broadly compatible version while leaving the original photo intact.", "Use our free online image converter when your browser can decode the HEIC file; processing begins on your device rather than through a file-upload queue."], bullets: ["Keep the original HEIC in case you need it later", "Create a JPG copy for a form, email or older app", "Open the JPG after conversion to confirm orientation and colour"] },
      { heading: "Steps for Windows and Android", paragraphs: ["Move the HEIC file onto the device you are using, then add it to the conversion queue. Choose JPG as the output format and download the finished copy with a new name.", "If a particular browser cannot decode the HEIC file, try a current browser on the same device or use the operating system's compatible photo application. Device and browser support can differ."], bullets: ["Add the HEIC photo", "Choose JPG", "Convert and inspect the output before submitting it"] },
      { heading: "Keep quality practical", paragraphs: ["JPG is lossy, so avoid repeatedly converting the same JPG. Start from the HEIC original whenever you need a new size or quality setting.", "For a website or email attachment, you can later compress the JPG copy after checking that the image still looks appropriate at its intended size." ] },
    ],
  },
  {
    slug: "raw-camera-files-to-jpg", category: "FORMAT FIXERS", title: "Convert RAW Camera Files to JPG", metaTitle: "Convert RAW Camera Files to JPG (Free Guide)", keyword: "convert raw to jpg without losing quality free", description: "A practical guide to converting RAW camera files to JPG while keeping originals safe and checking browser compatibility.", lead: "RAW files contain sensor data rather than a finished photograph, so a reliable conversion needs a decoder that understands the camera format.", reading: "7 min", tool: "convert", related: ["dng-to-jpg-without-lightroom", "safe-free-image-converters"], visual: { src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663909203131/rEZBzLGhmCqPiGXe.jpg", alt: "Camera sensor and memory card beside a finished JPG landscape print", title: "RAW Master to JPG Delivery Copy" },
    sections: [
      { heading: "Keep the RAW original", paragraphs: ["A JPG is a convenient deliverable, but it does not replace a CR2, NEF, ARW or DNG original. Keep the camera file in your archive and export JPG copies for sharing, print proofs or upload forms.", "Support varies by camera model, browser and RAW decoder. A trustworthy converter should report when a particular file cannot be decoded instead of delivering a misleading result."], bullets: ["Archive the original RAW file", "Use JPG for delivery and quick review", "Check colour, exposure and orientation in the exported file"] },
      { heading: "A practical browser workflow", paragraphs: ["Add one supported RAW file, select JPG and allow the browser time to decode it. Large camera files can use substantial memory, so close other intensive tabs before processing a big batch.", "If the file does not decode locally, use a desktop RAW application that explicitly supports that camera model. The right fallback is better than forcing an uncertain conversion." ] },
      { heading: "Quality does not mean zero change", paragraphs: ["RAW-to-JPG conversion always renders the sensor data into a finished image, so the result depends on the decoder and available settings. Compare the JPG at the size at which it will actually be viewed.", "Once the JPG is ready, use the compressor only when a smaller delivery copy is needed." ] },
    ],
  },
  {
    slug: "webp-to-jpg-any-device", category: "FORMAT FIXERS", title: "WebP to JPG on Any Device", metaTitle: "WebP to JPG: Convert Images on Any Device", keyword: "how to convert webp to jpg on iphone", description: "Learn how to save and convert WebP images to JPG on phones and computers while keeping a compatible copy for sharing.", lead: "WebP is efficient for the web, but JPG is still the easiest format to send into older apps, documents and forms.", reading: "5 min", tool: "convert", related: ["heic-to-jpg-windows-android", "png-vs-jpg-compression"], visual: { src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663909203131/dsayWhoqoPIkkrUs.jpg", alt: "Modern web image card becoming a classic JPG photo print", title: "WebP-to-JPG Compatibility Copy" },
    sections: [
      { heading: "Why convert WebP to JPG", paragraphs: ["A downloaded WebP file may not open in a legacy editor or may be rejected by a form that only accepts JPG. Make a JPG copy when compatibility matters more than the original web-optimised encoding.", "Use the free online image converter to convert WebP files locally here, then confirm the JPG opens in the destination application." ] },
      { heading: "Convert a WebP file", paragraphs: ["Save the WebP file first, add it to the converter, select JPG and convert the queue. The JPG copy is separate from the WebP original, so you can keep both if you need different delivery formats.", "For photographs, JPG is generally a sensible compatibility export. For art with crisp lines or transparency, PNG may be the better alternative."], bullets: ["Save the source file", "Select JPG output", "Open the completed JPG before attaching or uploading it"] },
      { heading: "Use the smallest practical copy", paragraphs: ["Format conversion and compression are separate choices. Convert WebP to JPG first when a JPG is required, then compress the JPG if an attachment or site has a size constraint.", "Avoid converting back and forth repeatedly, because each lossy export can change the image." ] },
    ],
  },
  {
    slug: "svg-to-png-high-resolution", category: "FORMAT FIXERS", title: "Convert SVG to High-Resolution PNG", metaTitle: "Convert SVG to High-Resolution PNG", keyword: "convert svg to png high resolution free", description: "Convert SVG artwork to a high-resolution PNG with clear steps for choosing dimensions and checking print or web output.", lead: "SVG remains sharp because it describes shapes rather than pixels, but many destinations require a fixed PNG image.", reading: "6 min", tool: "convert", related: ["png-vs-jpg-compression", "webp-to-jpg-any-device"], visual: { src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663909203131/umxchoIwcApyfsyD.jpg", alt: "Geometric vector lines resolving into a crisp PNG pixel tile", title: "SVG to High-Resolution PNG" },
    sections: [
      { heading: "Pick the destination dimensions first", paragraphs: ["Before rasterising a vector, decide where the PNG will be used. A social post, slide deck and print handoff each need different pixel dimensions.", "Rasterising at a larger size preserves more detail for a later downscale. Enlarging a small PNG afterwards cannot recreate vector detail."], bullets: ["List the destination width and height", "Use a larger pixel size for high-density displays", "Keep the original SVG for future exports"] },
      { heading: "Rasterise the vector safely", paragraphs: ["Add the SVG to the conversion queue and select PNG. The resulting PNG is a pixel-based copy, so inspect thin lines, text and transparent areas at the final size.", "Use our converter to rasterize your vectors safely on the device when the file and browser support the conversion path." ] },
      { heading: "Choose PNG or JPG deliberately", paragraphs: ["PNG is usually the right target for logos, flat illustrations and transparent artwork. JPG can be smaller for photographic imagery but does not preserve transparency.", "If a PNG becomes too heavy for a web page, test a compressed copy and compare the visible result instead of assuming a fixed percentage reduction." ] },
    ],
  },
  {
    slug: "reduce-image-size-50kb-100kb", category: "SIZE & COMPRESSION", title: "How to Reduce Image Size to 50KB or 100KB", metaTitle: "Reduce Image Size to 50KB or 100KB", keyword: "reduce image size to 50kb for online form", description: "A practical method to reduce photo size for online forms by controlling dimensions, quality and output format.", lead: "Online forms often set a hard size limit, so the goal is not a vague compression percentage: it is a file that opens cleanly under the limit.", reading: "7 min", tool: "compress", related: ["compress-images-for-website-seo", "passport-photo-size"], visual: { src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663909203131/gsKxfjyzMiprmMJw.jpg", alt: "Large photo card becoming a compact delivery image", title: "50 KB / 100 KB Image Size Workflow" },
    sections: [
      { heading: "Measure before changing anything", paragraphs: ["Check the form's stated limit and the image's current size. A 100KB target leaves little room for guesswork, so make a copy and reduce it in small, reviewable steps.", "Different images compress differently. A simple logo may shrink dramatically, while a detailed photo may need both a smaller dimension and lower quality."], bullets: ["Check the target in KB, not just MB", "Keep the original file", "Use the result row to compare original and output sizes"] },
      { heading: "Use size and dimensions together", paragraphs: ["Start with Balanced compression, then lower the maximum dimension only if the result is still too large. Reducing dimensions often has a stronger effect than pushing quality too far down.", "Use the compressor to shrink your photo to an exact size by iterating: compress, inspect the reported output size, then adjust settings if necessary." ] },
      { heading: "Confirm the form accepts the result", paragraphs: ["Open the completed file before uploading it. If the form rejects a format, create a compatible JPG or PNG copy first and then repeat the size adjustment.", "Do not rely on a filename alone; the final file size and actual image preview are what matter." ] },
    ],
  },
  {
    slug: "compress-images-for-website-seo", category: "SIZE & COMPRESSION", title: "Compress Images for Website SEO", metaTitle: "Compress Images for Website SEO", keyword: "compress images for website seo without losing quality", description: "Learn a practical workflow for compressing website images while balancing loading performance, dimensions and visual quality.", lead: "Website images should be as light as practical, but an aggressive setting that makes key visuals look poor is not an optimisation win.", reading: "6 min", tool: "compress", related: ["png-vs-jpg-compression", "batch-compress-images"], visual: { src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663909203131/WcDwMJjTrjbiODhr.jpg", alt: "Lightweight image cards moving into a fast web layout", title: "Website Image Compression Workflow" },
    sections: [
      { heading: "Start with the display size", paragraphs: ["Upload dimensions matter. A 4000-pixel photo shown at 800 pixels often carries more data than the page needs, even before quality is considered.", "Export a working copy near the largest display size, then compress it. This gives the image optimizer less unnecessary pixel data to carry." ] },
      { heading: "Match format to the asset", paragraphs: ["JPG or WebP are common choices for photos. PNG suits screenshots, graphics and images that need transparency. Test the format at the real display size rather than relying on a generic rule.", "Use the compressor to optimize your site assets instantly, then compare each output against the original in the context of the page." ] },
      { heading: "Review in the browser", paragraphs: ["A compression result that looks fine in a file preview can reveal banding or soft details in a full web layout. Review hero images, product photos and screenshots at the size visitors will see.", "Keep a higher-quality source file so a new export is easy if the design changes later." ] },
    ],
  },
  {
    slug: "send-large-photos-by-email", category: "SIZE & COMPRESSION", title: "Send Large Photos by Email", metaTitle: "Send Large Photos by Email (Free Guide)", keyword: "how to send large photos via email free", description: "Reduce large photo attachment sizes with practical file, format and compression choices before sending email.", lead: "A high-resolution photo can be larger than an email service allows, even when the image itself is not especially long or complex.", reading: "5 min", tool: "compress", related: ["reduce-image-size-50kb-100kb", "batch-compress-images"], visual: { src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663909203131/FJWAAyKHRutEZDON.jpg", alt: "Photo prints prepared for an envelope with a simple paperclip", title: "Email-Friendly Photo Export" },
    sections: [
      { heading: "Know the attachment limit", paragraphs: ["Check the email provider's current limit before preparing files. The encoded email attachment can be larger than the file on disk, so leave room under the published limit.", "If the recipient needs to print or edit the photo, ask what dimensions and format they actually need before compressing it." ] },
      { heading: "Create an email-friendly copy", paragraphs: ["Make a duplicate, choose a balanced quality setting and reduce dimensions if the photo is much larger than the recipient needs. A 1200 to 2000 pixel long edge is often easier to email than a full camera original, depending on use.", "Compress your images before attaching them, then reopen the result to ensure it still has the detail you intend to share." ] },
      { heading: "Send a sensible bundle", paragraphs: ["For several images, batch compression keeps the workflow consistent. Downloading a ZIP can make it easier to keep the files together where the recipient can accept archives.", "Keep the originals outside the email folder so a smaller delivery copy does not replace your archive." ] },
    ],
  },
  {
    slug: "batch-compress-images", category: "SIZE & COMPRESSION", title: "Batch Compress Multiple Images at Once", metaTitle: "Batch Compress Images Online (No Watermark)", keyword: "batch compress images online free no watermark", description: "Batch compress multiple images with one quality and scale setting, compare results and download a single ZIP file.", lead: "Compressing images one by one is repetitive when a set of photos, product images or screenshots needs the same delivery treatment.", reading: "6 min", tool: "compress", related: ["compress-images-for-website-seo", "send-large-photos-by-email"], visual: { src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663909203131/mHojkmVHFmaCKLvg.jpg", alt: "A batch of photo cards passing through a compression workflow", title: "Batch Image Compression Workflow" },
    sections: [
      { heading: "Prepare a clean batch", paragraphs: ["Gather copies of the images you want to deliver and remove obvious duplicates first. A consistent batch is easier to review and makes the same quality setting more meaningful.", "Keep an original folder separate from the delivery folder so the compressed files are easy to identify later." ] },
      { heading: "Apply one controlled setting", paragraphs: ["Drop multiple files into the batch compressor, choose a quality preset and set the maximum dimension. The queue processes available files using that selection.", "The result rows show original and output sizes, which lets you spot an image that needs a gentler setting before downloading the set." ] },
      { heading: "Download and review together", paragraphs: ["Use the ZIP download when more than one result is ready. Open a few representative images from the ZIP to check that photos, graphics and text-heavy screenshots still look appropriate.", "For mixed asset types, separate photos from logos or screenshots if they need different output formats or quality settings." ] },
    ],
  },
  {
    slug: "png-vs-jpg-compression", category: "SIZE & COMPRESSION", title: "PNG vs JPG: Which Should You Compress?", metaTitle: "PNG vs JPG: Which Format Compresses Best?", keyword: "difference between compressing png and jpg", description: "Understand when to compress PNG or JPG images by comparing transparency, visual content and practical file-size choices.", lead: "PNG and JPG solve different problems, so maximum savings depend on what the image contains and how it will be used.", reading: "6 min", tool: "compress", related: ["compress-images-for-website-seo", "svg-to-png-high-resolution"], visual: { src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663909203131/byBYmtwVzmspBgEs.jpg", alt: "Transparent graphic and photographic print compared side by side", title: "PNG and JPG Compression Comparison" },
    sections: [
      { heading: "Use JPG for photographic detail", paragraphs: ["JPG is designed for photographs and can often make a compact visual copy when some compression change is acceptable. It does not keep transparent areas.", "Compress your JPGs here when the image is a photo and the output will be viewed at a known size." ] },
      { heading: "Use PNG for transparency and crisp graphics", paragraphs: ["PNG works well for logos, UI captures and illustrations where sharp edges or transparency matter. It can be less efficient for a detailed photograph.", "Compress your PNGs here with the Preserve option when you need to keep PNG output and transparent areas." ] },
      { heading: "Choose from the result, not a slogan", paragraphs: ["Make a copy in the format that suits the asset, then compare file size and visual output. The smallest file is not automatically the best if it introduces visible artifacts or removes transparency you need.", "For websites, test the exported image in the page layout, especially for type-heavy graphics and hero photography." ] },
    ],
  },
  {
    slug: "safe-free-image-converters", category: "PRIVACY & SECURITY", title: "Are Free Online Image Converters Safe?", metaTitle: "Are Free Online Image Converters Safe?", keyword: "is it safe to use free online image converters", description: "Learn what to check before using a free online image converter, including uploads, privacy notices and local processing.", lead: "Convenience should not require guessing where a file goes, how long it is retained or who can access it.", reading: "7 min", tool: "convert", related: ["raw-camera-files-to-jpg", "local-image-compression-safety"],
    sections: [
      { heading: "Read the processing model first", paragraphs: ["A converter can run in a browser, upload a file to a server, or combine both approaches. The difference matters most for personal photos, client assets, source designs and camera originals.", "Before using a service, look for a plain explanation of whether the file is uploaded, whether it is retained and whether the result is processed on your device."], bullets: ["Check whether the service asks you to upload a file", "Read its privacy and retention information", "Use a separate copy when the original is important"] },
      { heading: "Use local processing when it fits", paragraphs: ["For supported files, a browser-based workflow can process a copy on the device. That avoids an upload step for that conversion path and makes it easier to keep sensitive work within your own environment.", "Use our local, no-upload converter for a compatible format, then inspect the result before sharing it." ] },
      { heading: "Do not confuse privacy with compatibility", paragraphs: ["A local approach is not a guarantee that every unusual file type will decode in every browser. RAW, PDF, design and niche formats may need a specialised application.", "It is better to receive a clear compatibility message than to assume an unsupported file was processed accurately." ] },
    ],
  },
  {
    slug: "convert-sensitive-images-without-upload", category: "PRIVACY & SECURITY", title: "Convert Sensitive Images Without Uploading", metaTitle: "Convert Sensitive Images Without Uploading", keyword: "convert documents to images offline free", description: "A practical checklist for preparing sensitive images locally without relying on a file-upload conversion service.", lead: "When an image contains private information, the workflow should be designed around what the destination needs and where every copy will live.", reading: "6 min", tool: "convert", related: ["safe-free-image-converters", "metadata-when-converting-images"],
    sections: [
      { heading: "Start with the least exposure", paragraphs: ["Decide whether you need to transform the original at all. If a recipient only needs a viewable copy, export a separate image and keep the source in a controlled folder.", "For supported image files, process your files in the browser rather than sending them to an upload service. This does not turn a browser into a replacement for a full document-security workflow."], bullets: ["Use a duplicate rather than the original", "Remove unneeded pages or regions before sharing", "Keep delivery copies separate from working files"] },
      { heading: "Understand document limits", paragraphs: ["A PDF can contain pages, fonts, forms, embedded images and other objects. Extracting images or rendering every page is not the same as converting a normal JPG or PNG.", "If a sensitive PDF needs reliable page extraction, use an approved desktop document tool with a workflow your organisation permits." ] },
      { heading: "Check the output before delivery", paragraphs: ["Open the resulting copy and review visible text, page edges, orientation and any information that should not be included. A conversion step is a good moment to catch an accidental crop or unwanted page.", "Then use the image compressor only if a smaller delivery copy is genuinely required." ] },
    ],
  },
  {
    slug: "safe-raw-file-workflow", category: "PRIVACY & SECURITY", title: "A Safer Way to Convert RAW Files", metaTitle: "Safe Way to Convert RAW Files Online", keyword: "safe way to convert raw files online", description: "Protect camera RAW files with a practical local-first workflow, compatible export choices and honest browser-support checks.", lead: "Photographers often need a small JPG quickly, but the camera original is one of the files least suited to casual handling.", reading: "7 min", tool: "convert", related: ["raw-camera-files-to-jpg", "safe-free-image-converters"],
    sections: [
      { heading: "Treat RAW as a master file", paragraphs: ["A camera RAW file preserves options for later rendering, so do not use a conversion request as a reason to replace or discard it. Create a separate delivery JPG and keep the original in your image archive.", "The exact support path can vary by camera model, file type and browser. Test one representative file before you run a large set." ] },
      { heading: "Choose the workflow for the risk", paragraphs: ["For a compatible camera file, a browser-based converter can keep processing on the device. For a client job, unusual camera model or colour-critical work, use the established desktop RAW software that the project requires.", "A safe workflow is not defined by a marketing label; it is defined by clear control of originals, exports and delivery copies." ] },
      { heading: "Export only what the recipient needs", paragraphs: ["A small review JPG, full-resolution print JPG and editable project file are different deliverables. Match the export to the recipient rather than sending a camera original when a preview is enough.", "Compress the JPG only after visual review if the delivery channel has a size limit." ] },
    ],
  },
  {
    slug: "local-image-compression-safety", category: "PRIVACY & SECURITY", title: "Are Free Image Compression Sites Safe?", metaTitle: "Are Free Image Compression Sites Safe?", keyword: "are free image compressor sites safe", description: "Learn how image compression sites handle files and how to choose a local browser-based compressor for supported images.", lead: "A smaller file can be helpful, but it should not require sending a portfolio, client image or personal photo into an unclear retention pipeline.", reading: "6 min", tool: "compress", related: ["safe-free-image-converters", "batch-compress-images"],
    sections: [
      { heading: "Ask where the image goes", paragraphs: ["Some compressors upload files to remote servers. Others can run supported compression in the browser. Check the service's description and privacy information before processing a sensitive asset.", "The key question is not whether a site calls itself free; it is whether it clearly explains file handling and gives you a workflow you can verify." ] },
      { heading: "Use local compression for compatible files", paragraphs: ["The browser compressor processes supported JPG, PNG, WebP, AVIF and HEIC files locally. You can adjust quality and dimensions, then compare the result size before downloading.", "Use the local compressor for a practical delivery copy, and retain the original outside the compressed-output folder." ] },
      { heading: "Review before you send", paragraphs: ["Compression changes an output file. Inspect detailed photos, gradients, text and transparent PNG artwork before attaching or publishing the result.", "For a batch, review a few representative images rather than assuming one setting is perfect for every file." ] },
    ],
  },
  {
    slug: "metadata-when-converting-images", category: "PRIVACY & SECURITY", title: "Reduce Metadata Exposure When Converting Images", metaTitle: "Reduce EXIF Metadata When Converting Images", keyword: "remove exif data when converting images free", description: "Learn how image conversion can create a fresh delivery copy and why you should verify metadata removal before sharing.", lead: "A photo can carry more than pixels, including camera settings, dates and sometimes location details. Privacy-sensitive sharing needs an intentional export step.", reading: "6 min", tool: "convert", related: ["safe-free-image-converters", "convert-sensitive-images-without-upload"],
    sections: [
      { heading: "Know what metadata can contain", paragraphs: ["EXIF and related metadata may include camera model, capture time, orientation and other fields. Some images may also contain location information, depending on device settings and export history.", "Before sharing a sensitive photo, decide whether the recipient needs the original metadata at all." ] },
      { heading: "Create a fresh delivery copy", paragraphs: ["Exporting a standard image through a browser conversion path creates a new output file. For many standard image routes, this avoids carrying over the source's original metadata structure, but you should not treat that as a universal guarantee for every format.", "Use our local converter to create a separate JPG, PNG or WebP delivery copy, then inspect the file with a metadata viewer if metadata removal is critical." ] },
      { heading: "Make verification part of the workflow", paragraphs: ["A conversion is not a legal or forensic metadata-cleansing guarantee. For regulated, safety-critical or location-sensitive images, use a dedicated metadata tool and verify the output with the method required by your organisation.", "Keep the metadata-free delivery copy separate from the original so you can retain a complete archive where appropriate." ] },
    ],
  },
  {
    slug: "avif-to-jpg-windows-mac", category: "EMERGING FORMATS", title: "Convert AVIF to JPG on Windows and Mac", metaTitle: "Convert AVIF to JPG on Windows and Mac", keyword: "convert avif to jpg windows 10 free", description: "Convert AVIF files to JPG with a browser-safe workflow and check compatibility before sharing the result.", lead: "AVIF can deliver efficient modern images, but some desktop applications and upload forms still expect JPG.", reading: "5 min", tool: "convert", related: ["webp-to-jpg-any-device", "png-vs-jpg-compression"],
    sections: [
      { heading: "Why AVIF needs a compatibility copy", paragraphs: ["Modern browsers can often display AVIF while a legacy desktop workflow or online form cannot. Creating a JPG copy is a practical compatibility step, not a reason to discard the AVIF source.", "Use a current browser to decode AVIF locally, then open the completed JPG in the destination application before you send it." ] },
      { heading: "Convert the file", paragraphs: ["Add the AVIF image to the free online image converter, choose JPG and convert. If the browser cannot decode the source file, try a current supported browser or a desktop image application.", "The output JPG is a new copy. Keep the original AVIF if it is the preferred web asset or archive format." ] },
      { heading: "Choose the next optimisation", paragraphs: ["If the JPG is intended for a size-limited form or email, compress it after conversion and check the visible result. If it is a website asset, test the final format and dimensions in the actual layout.", "Do not repeatedly re-export lossy formats when you can return to the AVIF source." ] },
    ],
  },
  {
    slug: "keep-png-background-transparent", category: "EMERGING FORMATS", title: "Keep a PNG Background Transparent Online", metaTitle: "Keep PNG Background Transparent Online", keyword: "make png transparent background online free no upload", description: "Keep existing PNG transparency during conversion and learn when a dedicated background-removal tool is required.", lead: "A transparent PNG is useful for logos, product cutouts and UI assets, but conversion choices can flatten the transparent background.", reading: "5 min", tool: "convert", related: ["png-vs-jpg-compression", "svg-to-png-high-resolution"],
    sections: [
      { heading: "Preserve transparency with PNG", paragraphs: ["If the source already has transparent areas, choose PNG output when you need to preserve them. JPG does not support alpha transparency and will flatten transparent areas onto a solid background.", "Use the local converter to process your transparent PNG securely, then open the output against a coloured background to confirm the transparency survived." ] },
      { heading: "Background removal is different", paragraphs: ["Making an opaque photographic background transparent requires selecting or detecting a subject. Format conversion alone does not reliably perform that visual editing task.", "Use a dedicated image editor or background-removal tool when the goal is to create transparency that does not already exist in the source." ] },
      { heading: "Keep a master copy", paragraphs: ["Retain the original PNG or design file, especially for logos and product assets. A separate PNG export can be optimised for web or email without replacing the source artwork.", "Use compression carefully for transparent graphics and inspect sharp edges before publishing." ] },
    ],
  },
  {
    slug: "passport-photo-size", category: "EMERGING FORMATS", title: "Reduce Photo Size for Passport Applications", metaTitle: "Reduce Photo Size for Passport Applications", keyword: "reduce photo size for passport online free", description: "Prepare a smaller passport or visa photo file by following the application rules and adjusting output size carefully.", lead: "Passport and visa portals often combine strict file-size limits with exact image dimensions, so a generic compression setting is rarely enough.", reading: "6 min", tool: "compress", related: ["reduce-image-size-50kb-100kb", "send-large-photos-by-email"],
    sections: [
      { heading: "Read the application specification", paragraphs: ["Check the official application requirements for dimensions, file format, file size, background, crop and recency. Those rules vary by authority and can change, so the official source is the only requirement that matters.", "Do not alter a photo in a way that breaks the application rules just to make a smaller file." ] },
      { heading: "Create a compliant delivery copy", paragraphs: ["Start from the required crop and dimensions, then use the image compressor to reduce file size in controlled steps. The result row makes it easy to compare output size with the portal's stated limit.", "Resize and compress your passport photo safely on the device, then reopen the final file before upload." ] },
      { heading: "Keep the original separate", paragraphs: ["Save the original and the application-specific copy with distinct names. If the form rejects the file, return to the source instead of recompressing an already heavily compressed copy.", "A lower file size does not prove the image meets biometric or composition rules; verify those separately." ] },
    ],
  },
  {
    slug: "dng-to-jpg-without-lightroom", category: "EMERGING FORMATS", title: "DNG to JPG Without Lightroom", metaTitle: "Convert DNG to JPG Without Lightroom", keyword: "convert dng to jpg free online", description: "Learn practical DNG-to-JPG conversion steps, browser compatibility limits and how to protect the original digital negative.", lead: "DNG is a digital negative format, so a JPG export is a rendered delivery copy rather than a replacement for the original file.", reading: "7 min", tool: "convert", related: ["raw-camera-files-to-jpg", "safe-raw-file-workflow"],
    sections: [
      { heading: "Keep the DNG file", paragraphs: ["A DNG contains camera image data and can preserve editing flexibility that a JPG does not. Store the DNG as the master and create a JPG only for a recipient, preview or upload path that needs it.", "Decoding availability depends on browser and file characteristics, so test one DNG before preparing a large set." ] },
      { heading: "Create a compatible JPG copy", paragraphs: ["Add the DNG to the conversion queue, choose JPG and review the output. If the local decoder cannot handle that file, use a desktop RAW application that supports the camera and DNG variant.", "Convert your DNG files through a compatible local path, and avoid treating an unsupported-browser message as a finished conversion." ] },
      { heading: "Check the rendered image", paragraphs: ["Compare exposure, crop, orientation and colour in the JPG at its intended display size. For critical work, use the camera or photography software that gives you the needed rendering controls.", "Compress the final JPG only when a smaller delivery copy is needed." ] },
    ],
  },
  {
    slug: "extract-images-from-pdf", category: "EMERGING FORMATS", title: "How to Extract Images from a PDF", metaTitle: "How to Extract Images from a PDF", keyword: "extract images from pdf free online no upload", description: "Understand the difference between extracting embedded PDF images and rendering pages, with practical privacy and compatibility considerations.", lead: "A PDF can hold embedded images, vector artwork, text and full page layouts, so extraction is not the same task as opening an ordinary photo.", reading: "7 min", tool: "convert", related: ["convert-sensitive-images-without-upload", "reduce-image-size-50kb-100kb"],
    sections: [
      { heading: "Choose extraction or page rendering", paragraphs: ["Extracting an embedded image preserves the original object when the PDF contains one. Rendering a page creates a new image of everything visible on that page, including text and layout.", "Decide which result you need before choosing a tool. A rendered page may be appropriate for a visual proof but is not a substitute for the original embedded asset." ] },
      { heading: "Use a compatible local workflow", paragraphs: ["PDF support in browser tools can vary because documents may contain fonts, forms, security settings and complex graphics. For sensitive or important PDFs, use an approved desktop PDF tool that can clearly extract the image or render the required pages.", "A browser-based image converter can handle compatible image files locally, but should not be presented as a universal PDF extraction guarantee." ] },
      { heading: "Review the result before sharing", paragraphs: ["Open the output image and check crop, resolution and visible text. If the PDF contains personal or confidential information, confirm that the rendered page does not include more than the recipient needs.", "For delivery limits, create a separate compressed copy after the page image has been verified." ] },
    ],
  },
];

export function articleBySlug(slug?: string) { return articles.find((article) => article.slug === slug); }
